client_id: 3MVG9Y6d_Btp4xp7Qo8BT7q1upXKZdMa7eVPpqzEGF9MXOVGyIAJokvidKVl3j6sgudvUeNlYVAYZNuoGcsI9
client_secret: 7487495796300256924
username: stephen.moss@69demo.com
password: Punisher#01Nza2DlTvLBqDf1vjO4QpJXC9p
host: login.salesforce.com
debugging: true